---
# *`MULTIPLE LINEAR REGRESSION ALGORITHM`*

In [117]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from  sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score , mean_absolute_percentage_error
import numpy as np

In [118]:
df = pd.read_csv(r"C:\Users\Muhammad Yahya\Downloads\python\AI Roadmap2026\AI_Road_Map_2026\Module05_MachineLearning\SupervisedLearning\Lect02_Multivariate_Linear_Regression\multiple_linear_regression_dataset.csv")
df

    age  experience  income
0    25           1   30450
1    30           3   35670
2    47           2   31580
3    32           5   40130
4    43          10   47830
5    51           7   41630
6    28           5   41340
7    33           4   37650
8    37           5   40250
9    39           8   45150
10   29           1   27840
11   47           9   46110
12   54           5   36720
13   51           4   34800
14   44          12   51300
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700

In [119]:
mean = df.experience.mean()
mean

np.float64(6.2)

In [120]:
median = df.experience.median()
median

np.float64(5.0)

In [121]:
df['experience'][16] = df.experience.mean()
df

C:\Users\Muhammad Yahya\AppData\Local\Temp\ipykernel_13020\4084046647.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '6.2' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df['experience'][16] = df.experience.mean()

    age  experience  income
0    25         1.0   30450
1    30         3.0   35670
2    47         2.0   31580
3    32         5.0   40130
4    43        10.0   47830
5    51         7.0   41630
6    28         5.0   41340
7    33         4.0   37650
8    37         5.0   40250
9    39         8.0   45150
10   29         1.0   27840
11   47         9.0   46110
12   54         5.0   36720
13   51         4.0   34800
14   44        12.0   51300
15   41         6.0   38900
16   58         6.2   63600
17   23         1.0   30870
18   44         9.0   44190
19   37        10.0   48700

### Seperate dependent or independents feature

In [122]:
X = df[['age' , 'experience']]
y = df['income']

### Split data (Training or Testing Purpose)

In [123]:
X_train , X_test , y_train , y_test = train_test_split(X , y ,  test_size=0.2 , random_state=42)

### Build Model

In [124]:
model = LinearRegression().fit(X_train , y_train)
model

LinearRegression()

### Prediction

In [125]:
y_hat = model.predict([[37 , 10.1]])
y_hat

C:\Users\Muhammad Yahya\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([48065.79692408])

### Coefficients/Slops

In [126]:
model.coef_

array([ 222.93142455, 1826.82032994])

### Intercept

In [127]:
model.intercept_

np.float64(21366.448883240453)

### `Manual Calculation`

In [128]:
m1 = 222.93142455
m2 = 1826.82032994
b = 21366.448883240453

x1 = age = 37
x2 = experience = 10.1


y = income = (m1*age + m2*experience) + b
income

48065.79692398445

In [129]:
if np.round(income) == np.round(y_hat):
    print(f"Manual Calculation is {True}")

else:
    print(f"Manual Calculation is {False}")

Manual Calculation is True