# **Making Series & DataFrame**

In [1]:
import pandas as pd

In [122]:
s1 = pd.Series([12 , 15 , 5 , 6 ,9 , 10])
s1

0    12
1    15
2     5
3     6
4     9
5    10
dtype: int64

Customize Index Labels

In [123]:
s2 = pd.Series([12 , 15 , 5 , 6 ,9 , 10] , index=['eggs' , 'bananas' , 'apple' , 'orange' , 'guava' , 'dates'])
print(s2)
print(s2.ndim,'Dimension')

eggs       12
bananas    15
apple       5
orange      6
guava       9
dates      10
dtype: int64
1 Dimension

In [124]:
s1[1]

np.int64(15)

In [125]:
s2['bananas']

np.int64(15)

In [126]:
s1[0:4]

0    12
1    15
2     5
3     6
dtype: int64

Difference B/W s1 & s2 slicing

```python
s1[0:4]
s2['eggs':'orange']

In [127]:
s2['eggs':'orange']

eggs       12
bananas    15
apple       5
orange      6
dtype: int64

In [128]:
s1[2:4]

2    5
3    6
dtype: int64

In [129]:
s2['apple':'guava']

apple     5
orange    6
guava     9
dtype: int64

---

In [130]:
s3 = pd.Series(['Usman' , 'Umair' , 'Imtiaz'] , index=[101 , 102 , 103] , name='Students')
s3

101     Usman
102     Umair
103    Imtiaz
Name: Students, dtype: object

In [131]:
s3.values

array(['Usman', 'Umair', 'Imtiaz'], dtype=object)

In [132]:
type(s3.values)

numpy.ndarray

In [133]:
s3.index

Index([101, 102, 103], dtype='int64')

In [134]:
type(s3.index)

pandas.core.indexes.base.Index

In [135]:
s3.name

'Students'

In [136]:
# DataFrame

df = pd.DataFrame([

    1 , 2 , 4 , 6 , 8 
    
    ])

df

   0
0  1
1  2
2  4
3  6
4  8

In [137]:
df2 = pd.DataFrame(

    [1 , 2 , 4 , 6 , 8 ] , index=['banana' , 'orange' , 'apple' , 'eggs' , 'cakes']

    )

df2

        0
banana  1
orange  2
apple   4
eggs    6
cakes   8

In [138]:
df2['banana':'apple']

        0
banana  1
orange  2
apple   4

In [139]:
df[0:3]

   0
0  1
1  2
2  4

In [140]:
df2 = pd.DataFrame(

    [1 , 2 , 4 , 6 , 8 ], 
    index=['banana' , 'orange' , 'apple' , 'eggs' , 'cakes'], 
    columns=['Foods']

    )

df2

        Foods
banana      1
orange      2
apple       4
eggs        6
cakes       8

In [141]:
df3 = pd.DataFrame(

    {
        'Apple':[100 , 150],
        'Banana':[111 , 24]

    },
    index=['Tree#01' , 'Tree#02']

)

df3

         Apple  Banana
Tree#01    100     111
Tree#02    150      24

In [142]:
df3.Apple

Tree#01    100
Tree#02    150
Name: Apple, dtype: int64

In [143]:
df3['Apple']

Tree#01    100
Tree#02    150
Name: Apple, dtype: int64

In [144]:
df3['Tree#01':'Tree#01']

         Apple  Banana
Tree#01    100     111

In [145]:
df4 = pd.DataFrame(

    {
        'Apple':[100 , 150],
        'Banana':[111 , 24]

    },
    index=[1 , 2]

)

df4

   Apple  Banana
1    100     111
2    150      24

In [146]:
df4[0:1]

   Apple  Banana
1    100     111

Difference B/W df3 or df4

```python
df4[0:1]

Apple	Banana
1	100	111

df3['Tree#01':'Tree#02']

Apple	Banana
Tree#01	100	111
Tree#02	150	24

In [147]:
df3['Tree#01':'Tree#02']

         Apple  Banana
Tree#01    100     111
Tree#02    150      24

In [148]:
df5 = pd.DataFrame(

    {
        'Apple':100,
        'Banana':200

    },

    index=[0 , 1 , 2]

)

df5

   Apple  Banana
0    100     200
1    100     200
2    100     200

# **Adding With Columns**

```Adding a new column in an existing DataFrame```

In [149]:
df5['Orange'] = 500
df5

   Apple  Banana  Orange
0    100     200     500
1    100     200     500
2    100     200     500

# **Updating And Existing Column**

In [150]:
df5['Apple'] = 1000
df5

   Apple  Banana  Orange
0   1000     200     500
1   1000     200     500
2   1000     200     500

# **Deleting And Existing Column**

In [151]:
del df5['Banana']
df5

   Apple  Orange
0   1000     500
1   1000     500
2   1000     500

In [152]:
df6 = pd.DataFrame(

    {
        'Apple':[100 , 2010 , 1900],
        'Banana':[200 , 1999 , 100]

    },

    index=['Tree01', 'Tree02', 'Tree03']

)

df6

        Apple  Banana
Tree01    100     200
Tree02   2010    1999
Tree03   1900     100

In [169]:
# broadcasting a constant value to all records
df6['Orange'] = 800
df6

        Apple  Banana  Orange
Tree01    100     200     800
Tree02   2010    1999     800
Tree03   1900     100     800

# **List Comprehension**

In [ ]:
# without List Comprehension
lst = [20 , 21 , 22 , 23 , 24]

emp_lst = []

for i in lst:

    emp_lst.append(i*0.25)

emp_lst

[5.0, 5.25, 5.5, 5.75, 6.0]

In [176]:
# Now Using List Comprehension
[i*0.25 for i in lst]

[5.0, 5.25, 5.5, 5.75, 6.0]

In [178]:
[a*2 for a in range(100-90)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
fruit_box = [apple*3 for apple in range(1 , 10)]
fruit_box

[3, 6, 9, 12, 15, 18, 21, 24, 27]

In [195]:
even_num = [even for even in range(1 , 31) if even%2==0]
even_num

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]

In [196]:
odd_num = [odd for odd in range(30) if odd%2 == 1]
odd_num

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

# Important
---
```python
agr 'conditional statement' sy only if use kr rahy hain tou 'list comprehension' main 'for loop' k baad 'if' use hoga.

agr 'if else' donoun use krna ha 'list comprehension' main phir 'for loop' sy pehly 'if else' use hota ha. 

jesy below

In [ ]:
[even if even%2 == 0 else 'odd'  for even in range(1 , 31)]

['odd',
 2,
 'odd',
 4,
 'odd',
 6,
 'odd',
 8,
 'odd',
 10,
 'odd',
 12,
 'odd',
 14,
 'odd',
 16,
 'odd',
 18,
 'odd',
 20,
 'odd',
 22,
 'odd',
 24,
 'odd',
 26,
 'odd',
 28,
 'odd',
 30]

Generating Data From Data Using List Comprehension

In [11]:
df7 = pd.DataFrame(

    {
        'Apple':[100 , 2010 , 1900 , 1001],
        'Banana':[200 , 1999 , 100 , 2006],
        'Orange':[100 , 199 , 1010 , 206]

    },

    index=['Tree01', 'Tree02', 'Tree03' , 'Tree04']

)

df7

        Apple  Banana  Orange
Tree01    100     200     100
Tree02   2010    1999     199
Tree03   1900     100    1010
Tree04   1001    2006     206

In [12]:
df7['Guava'] = [n+n*0.95 if n<=100 else n>100 if n==1001 else n>1001 for n in df7['Apple']]
df7

        Apple  Banana  Orange  Guava
Tree01    100     200     100  195.0
Tree02   2010    1999     199   True
Tree03   1900     100    1010   True
Tree04   1001    2006     206   True

In [13]:
df7['Guava'] = [n+n*0.95 if n>=1000 else n-n*0.5 if n<1000 else n-n*0.9 for n in df7['Apple']]
df7

        Apple  Banana  Orange    Guava
Tree01    100     200     100    50.00
Tree02   2010    1999     199  3919.50
Tree03   1900     100    1010  3705.00
Tree04   1001    2006     206  1951.95

In [23]:
df7['Cherry'] = [n+n*0.97 
                 if n>=50.99 
                 else n+n*1.99 
                 for n in df7['Guava']]
df7

        Apple  Banana  Orange    Guava     Cherry
Tree01    100     200     100    50.00   149.5000
Tree02   2010    1999     199  3919.50  7721.4150
Tree03   1900     100    1010  3705.00  7298.8500
Tree04   1001    2006     206  1951.95  3845.3415

In [31]:
df7['Total'] = df7['Apple'] + df7['Banana'] + df7['Orange'] + df7['Guava'] + df7['Cherry'] / 6
df7

        Apple  Banana  Orange    Guava     Cherry        Total
Tree01    100     200     100    50.00   149.5000   474.916667
Tree02   2010    1999     199  3919.50  7721.4150  9414.402500
Tree03   1900     100    1010  3705.00  7298.8500  7931.475000
Tree04   1001    2006     206  1951.95  3845.3415  5805.840250

In [57]:
df7['percentage'] = round(df7['Total']/10000*100 , 2)
df7

        Apple  Banana  Orange    Guava     Cherry        Total  percentage
Tree01    100     200     100    50.00   149.5000   474.916667        4.75
Tree02   2010    1999     199  3919.50  7721.4150  9414.402500       94.14
Tree03   1900     100    1010  3705.00  7298.8500  7931.475000       79.31
Tree04   1001    2006     206  1951.95  3845.3415  5805.840250       58.06

---
# `IMPORT LIBRARY`

In [154]:
import pandas as pd

# Load DataSet

In [155]:
call_csv = pd.read_csv(r'C:\Users\Muhammad Yahya\Downloads\python\AI Roadmap2026\AI_Road_Map_2026\Module04_Pandas\student_performance_dataset-selected-columns.csv')
call_csv

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8
...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4

# CALL TOP FIVE ROWS

In [156]:
top_five = call_csv.head()
top_five

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8

# BOTTOM FIVE ROWS

In [157]:
bot_five = call_csv.tail()
bot_five

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4

# CHECK TOTAL ROWS & COLUMNS

In [158]:
check_rows_col = call_csv.shape
check_rows_col

(1000, 10)

# CALL COLUMN

In [159]:
call_col = call_csv['parental_education']
call_col

0        Bachelors
1      High School
2        Bachelors
3              NaN
4        Bachelors
          ...
995        Masters
996            NaN
997    High School
998    High School
999        Masters
Name: parental_education, Length: 1000, dtype: object

# CALL MORE COLUMNS

In [160]:
call_more_col = call_csv[['student_id','parental_education']]
call_more_col

     student_id parental_education
0             1          Bachelors
1             2        High School
2             3          Bachelors
3             4                NaN
4             5          Bachelors
..          ...                ...
995         996            Masters
996         997                NaN
997         998        High School
998         999        High School
999        1000            Masters

[1000 rows x 2 columns]

# CALL MIN VALUE

In [161]:
call_min = call_csv['attendance_percent'].min()
call_min

np.float64(54.8)

In [162]:
call_min = call_csv['attendance_percent'].max()
call_min

np.float64(100.0)

In [163]:
call_min = call_csv[['sleep_hours','attendance_percent']].max()
call_min

sleep_hours            10.0
attendance_percent    100.0
dtype: float64

# CALL HIGHEST ATTENDANCE PERCENTAGE

In [164]:
highest_percent_call = call_csv[call_csv['attendance_percent'] == 100]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5
6,7,Male,1.5,100.0,5.0,High School,Yes,Yes,Yes,58.6
21,22,Male,3.3,100.0,7.8,NaN,Yes,Yes,No,83.9
27,28,Female,5.4,100.0,5.7,High School,No,No,No,83.3
32,33,Female,5.3,100.0,7.3,Masters,Yes,Yes,No,67.7
...,...,...,...,...,...,...,...,...,...,...
918,919,Female,4.3,100.0,8.1,PhD,Yes,Yes,No,84.8
919,920,Female,2.2,100.0,8.1,High School,Yes,No,Yes,66.9
925,926,Male,4.7,100.0,7.3,Bachelors,Yes,No,No,57.4
937,938,Male,4.2,100.0,7.1,PhD,No,Yes,Yes,65.6
979,980,Female,3.3,100.0,9.1,High School,Yes,Yes,No,64.0

# CHECK RANDOMLY

In [165]:
highest_percent_call = call_csv[call_csv['attendance_percent'] == 70]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
396,397,Female,4.1,70.0,5.4,High School,Yes,Yes,No,70.3
549,550,Male,2.7,70.0,8.6,High School,Yes,No,No,68.1
913,914,Female,4.0,70.0,8.2,Masters,Yes,Yes,No,79.5

In [166]:
highest_percent_call = call_csv[call_csv['attendance_percent'] == 99.9]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
172,173,Male,4.1,99.9,7.2,NaN,Yes,No,No,43.4
759,760,Male,3.5,99.9,7.4,Bachelors,No,Yes,Yes,69.8

In [167]:
highest_percent_call = call_csv[call_csv['attendance_percent'] == 90]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
361,362,Male,2.4,90.0,5.4,Masters,Yes,No,Yes,100.0
527,528,Female,5.9,90.0,7.7,Masters,Yes,No,No,69.7
545,546,Female,6.3,90.0,6.3,High School,Yes,Yes,No,85.1
776,777,Male,1.4,90.0,6.2,Bachelors,Yes,Yes,No,82.3
927,928,Female,4.3,90.0,5.6,Masters,Yes,No,No,79.1
950,951,Male,2.6,90.0,5.2,NaN,No,No,No,67.3
987,988,Female,1.1,90.0,9.0,High School,Yes,Yes,No,67.0

In [168]:
highest_percent_call = call_csv[call_csv['attendance_percent']  <= 56]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
205,206,Male,2.8,55.8,6.3,Bachelors,Yes,Yes,Yes,76.1
585,586,Male,2.5,55.6,6.7,Bachelors,Yes,Yes,No,64.8
638,639,Female,6.1,54.8,4.6,Masters,Yes,No,No,83.0