# **Making Series & DataFrame**

In [1]:
import pandas as pd

In [4]:
s1 = pd.Series([12 , 15 , 5 , 6 ,9 , 10])
s1

0    12
1    15
2     5
3     6
4     9
5    10
dtype: int64

Customize Index Labels

In [ ]:
s2 = pd.Series([12 , 15 , 5 , 6 ,9 , 10] , index=['eggs' , 'bananas' , 'apple' , 'orange' , 'guava' , 'dates'])
print(s2)
print(s2.ndim,'Dimension')

eggs       12
bananas    15
apple       5
orange      6
guava       9
dates      10
dtype: int64
1 Dimension

In [14]:
s1[1]

np.int64(15)

In [13]:
s2['bananas']

np.int64(15)

In [15]:
s1[0:4]

0    12
1    15
2     5
3     6
dtype: int64

Difference B/W s1 & s2 slicing

```python
s1[0:4]
s2['eggs':'orange']

In [16]:
s2['eggs':'orange']

eggs       12
bananas    15
apple       5
orange      6
dtype: int64

In [17]:
s1[2:4]

2    5
3    6
dtype: int64

In [19]:
s2['apple':'guava']

apple     5
orange    6
guava     9
dtype: int64

---

In [24]:
s3 = pd.Series(['Usman' , 'Umair' , 'Imtiaz'] , index=[101 , 102 , 103] , name='Students')
s3

101     Usman
102     Umair
103    Imtiaz
Name: Students, dtype: object

In [23]:
s3.values

array(['Usman', 'Umair', 'Imtiaz'], dtype=object)

In [29]:
type(s3.values)

numpy.ndarray

In [25]:
s3.index

Index([101, 102, 103], dtype='int64')

In [28]:
type(s3.index)

pandas.core.indexes.base.Index

In [30]:
s3.name

'Students'

In [36]:
# DataFrame

df = pd.DataFrame([

    1 , 2 , 4 , 6 , 8 
    
    ])

df

   0
0  1
1  2
2  4
3  6
4  8

In [40]:
df2 = pd.DataFrame(

    [1 , 2 , 4 , 6 , 8 ] , index=['banana' , 'orange' , 'apple' , 'eggs' , 'cakes']

    )

df2

        0
banana  1
orange  2
apple   4
eggs    6
cakes   8

In [42]:
df2['banana':'apple']

        0
banana  1
orange  2
apple   4

In [43]:
df[0:3]

   0
0  1
1  2
2  4

In [46]:
df2 = pd.DataFrame(

    [1 , 2 , 4 , 6 , 8 ], 
    index=['banana' , 'orange' , 'apple' , 'eggs' , 'cakes'], 
    columns=['Foods']

    )

df2

        Foods
banana      1
orange      2
apple       4
eggs        6
cakes       8

In [ ]:
df3 = pd.DataFrame(

    {
        'Apple':[100 , 150],
        'Banana':[111 , 24]

    },
    index=['Tree#01' , 'Tree#02']

)

df3

         Apple  Banana
Tree#01    100     111
Tree#02    150      24

In [53]:
df3.Apple

Tree#01    100
Tree#02    150
Name: Apple, dtype: int64

In [54]:
df3['Apple']

Tree#01    100
Tree#02    150
Name: Apple, dtype: int64

In [57]:
df3['Tree#01':'Tree#01']

         Apple  Banana
Tree#01    100     111

In [65]:
df4 = pd.DataFrame(

    {
        'Apple':[100 , 150],
        'Banana':[111 , 24]

    },
    index=[1 , 2]

)

df4

   Apple  Banana
1    100     111
2    150      24

In [68]:
df4[0:1]

   Apple  Banana
1    100     111

Difference B/W df3 or df4

```python
df4[0:1]

Apple	Banana
1	100	111

df3['Tree#01':'Tree#02']

Apple	Banana
Tree#01	100	111
Tree#02	150	24

In [69]:
df3['Tree#01':'Tree#02']

         Apple  Banana
Tree#01    100     111
Tree#02    150      24

In [ ]:
df5 = pd.DataFrame(

    {
        'Apple':100,
        'Banana':200

    },

    index=[0]

)

df5

   Apple  Banana
0    100     200

---
# `IMPORT LIBRARY`

In [30]:
import pandas as pd

# Load DataSet

In [31]:
call_csv = pd.read_csv(r'C:\Users\Muhammad Yahya\Downloads\python\AI Roadmap2026\Module03 Pandas\student_performance_dataset-selected-columns.csv')
call_csv

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8
...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4

# CALL TOP FIVE ROWS

In [32]:
top_five = call_csv.head()
top_five

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8

# BOTTOM FIVE ROWS

In [33]:
bot_five = call_csv.tail()
bot_five

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4

# CHECK TOTAL ROWS & COLUMNS

In [34]:
check_rows_col = call_csv.shape
check_rows_col

(1000, 10)

# CALL COLUMN

In [35]:
call_col = call_csv['parental_education']
call_col

0        Bachelors
1      High School
2        Bachelors
3              NaN
4        Bachelors
          ...
995        Masters
996            NaN
997    High School
998    High School
999        Masters
Name: parental_education, Length: 1000, dtype: object

# CALL MORE COLUMNS

In [36]:
call_more_col = call_csv[['student_id','parental_education']]
call_more_col

     student_id parental_education
0             1          Bachelors
1             2        High School
2             3          Bachelors
3             4                NaN
4             5          Bachelors
..          ...                ...
995         996            Masters
996         997                NaN
997         998        High School
998         999        High School
999        1000            Masters

[1000 rows x 2 columns]

# CALL MIN VALUE

In [37]:
call_min = call_csv['attendance_percent'].min()
call_min

np.float64(54.8)

In [38]:
call_min = call_csv['attendance_percent'].max()
call_min

np.float64(100.0)

In [39]:
call_min = call_csv[['sleep_hours','attendance_percent']].max()
call_min

sleep_hours            10.0
attendance_percent    100.0
dtype: float64

# CALL HIGHEST ATTENDANCE PERCENTAGE

In [40]:
highest_percent_call = call_csv[call_csv['attendance_percent'] == 100]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5
6,7,Male,1.5,100.0,5.0,High School,Yes,Yes,Yes,58.6
21,22,Male,3.3,100.0,7.8,NaN,Yes,Yes,No,83.9
27,28,Female,5.4,100.0,5.7,High School,No,No,No,83.3
32,33,Female,5.3,100.0,7.3,Masters,Yes,Yes,No,67.7
...,...,...,...,...,...,...,...,...,...,...
918,919,Female,4.3,100.0,8.1,PhD,Yes,Yes,No,84.8
919,920,Female,2.2,100.0,8.1,High School,Yes,No,Yes,66.9
925,926,Male,4.7,100.0,7.3,Bachelors,Yes,No,No,57.4
937,938,Male,4.2,100.0,7.1,PhD,No,Yes,Yes,65.6
979,980,Female,3.3,100.0,9.1,High School,Yes,Yes,No,64.0

# CHECK RANDOMLY

In [41]:
highest_percent_call = call_csv[call_csv['attendance_percent'] == 70]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
396,397,Female,4.1,70.0,5.4,High School,Yes,Yes,No,70.3
549,550,Male,2.7,70.0,8.6,High School,Yes,No,No,68.1
913,914,Female,4.0,70.0,8.2,Masters,Yes,Yes,No,79.5

In [42]:
highest_percent_call = call_csv[call_csv['attendance_percent'] == 99.9]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
172,173,Male,4.1,99.9,7.2,NaN,Yes,No,No,43.4
759,760,Male,3.5,99.9,7.4,Bachelors,No,Yes,Yes,69.8

In [45]:
highest_percent_call = call_csv[call_csv['attendance_percent'] == 90]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
361,362,Male,2.4,90.0,5.4,Masters,Yes,No,Yes,100.0
527,528,Female,5.9,90.0,7.7,Masters,Yes,No,No,69.7
545,546,Female,6.3,90.0,6.3,High School,Yes,Yes,No,85.1
776,777,Male,1.4,90.0,6.2,Bachelors,Yes,Yes,No,82.3
927,928,Female,4.3,90.0,5.6,Masters,Yes,No,No,79.1
950,951,Male,2.6,90.0,5.2,NaN,No,No,No,67.3
987,988,Female,1.1,90.0,9.0,High School,Yes,Yes,No,67.0

In [54]:
highest_percent_call = call_csv[call_csv['attendance_percent']  <= 56]
highest_percent_call

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade
205,206,Male,2.8,55.8,6.3,Bachelors,Yes,Yes,Yes,76.1
585,586,Male,2.5,55.6,6.7,Bachelors,Yes,Yes,No,64.8
638,639,Female,6.1,54.8,4.6,Masters,Yes,No,No,83.0